// Hand-curated daily seed pairs with confirmed co-starring films
const DAILY_SEEDS = [
  { date: "2025-01-01", actorA: { id: 31,    name: "Tom Hanks"         }, actorB: { id: 6193,  name: "Robin Wright"      }, sharedFilm: "Forrest Gump" },
  { date: "2025-01-02", actorA: { id: 287,   name: "Brad Pitt"         }, actorB: { id: 1333,  name: "Morgan Freeman"    }, sharedFilm: "Se7en" },
  { date: "2025-01-03", actorA: { id: 6384,  name: "Keanu Reeves"      }, actorB: { id: 2975,  name: "Laurence Fishburne"}, sharedFilm: "The Matrix" },
  { date: "2025-01-04", actorA: { id: 192,   name: "Morgan Freeman"    }, actorB: { id: 3084,  name: "Jack Nicholson"    }, sharedFilm: "The Bucket List" },
  { date: "2025-01-05", actorA: { id: 1245,  name: "Scarlett Johansson"}, actorB: { id: 16828, name: "Bill Murray"       }, sharedFilm: "Lost in Translation" },
  { date: "2025-01-06", actorA: { id: 8784,  name: "Daniel Day-Lewis"  }, actorB: { id: 10182, name: "Paul Dano"         }, sharedFilm: "There Will Be Blood" },
  { date: "2025-01-07", actorA: { id: 2037,  name: "Meryl Streep"      }, actorB: { id: 2632,  name: "Dustin Hoffman"    }, sharedFilm: "Kramer vs. Kramer" },
  { date: "2025-01-08", actorA: { id: 3223,  name: "Robert Downey Jr." }, actorB: { id: 17419, name: "Gwyneth Paltrow"   }, sharedFilm: "Iron Man" },
  { date: "2025-01-09", actorA: { id: 73457, name: "Chris Evans"       }, actorB: { id: 3223,  name: "Robert Downey Jr." }, sharedFilm: "The Avengers" },
  { date: "2025-01-10", actorA: { id: 2524,  name: "Al Pacino"         }, actorB: { id: 1158,  name: "Robert De Niro"    }, sharedFilm: "The Godfather Part II" },
  { date: "2025-01-11", actorA: { id: 1158,  name: "Robert De Niro"    }, actorB: { id: 2975,  name: "Laurence Fishburne"}, sharedFilm: "The Score" },
  { date: "2025-01-12", actorA: { id: 1100,  name: "Jack Nicholson"    }, actorB: { id: 8167,  name: "Diane Keaton"      }, sharedFilm: "Something's Gotta Give" },
  { date: "2025-01-13", actorA: { id: 5064,  name: "Cate Blanchett"    }, actorB: { id: 2037,  name: "Meryl Streep"      }, sharedFilm: "The Aviator" },
  { date: "2025-01-14", actorA: { id: 4724,  name: "Heath Ledger"      }, actorB: { id: 1327,  name: "Christian Bale"    }, sharedFilm: "The Dark Knight" },
  { date: "2025-01-15", actorA: { id: 1327,  name: "Christian Bale"    }, actorB: { id: 2888,  name: "Hugh Jackman"      }, sharedFilm: "The Prestige" },
  { date: "2025-01-16", actorA: { id: 500,   name: "Tom Cruise"        }, actorB: { id: 1892,  name: "Nicole Kidman"     }, sharedFilm: "Eyes Wide Shut" },
  { date: "2025-01-17", actorA: { id: 2231,  name: "Edward Norton"     }, actorB: { id: 287,   name: "Brad Pitt"         }, sharedFilm: "Fight Club" },
  { date: "2025-01-18", actorA: { id: 6193,  name: "Robin Wright"      }, actorB: { id: 1813,  name: "Sean Penn"         }, sharedFilm: "She's So Lovely" },
  { date: "2025-01-19", actorA: { id: 1892,  name: "Nicole Kidman"     }, actorB: { id: 2037,  name: "Meryl Streep"      }, sharedFilm: "The Hours" },
  { date: "2025-01-20", actorA: { id: 1813,  name: "Sean Penn"         }, actorB: { id: 192,   name: "Morgan Freeman"    }, sharedFilm: "Milk" },
  { date: "2025-01-21", actorA: { id: 287,   name: "Brad Pitt"         }, actorB: { id: 5064,  name: "Cate Blanchett"    }, sharedFilm: "Babel" },
  { date: "2025-01-22", actorA: { id: 6384,  name: "Keanu Reeves"      }, actorB: { id: 1100,  name: "Jack Nicholson"    }, sharedFilm: "Something's Gotta Give" },
  { date: "2025-01-23", actorA: { id: 3223,  name: "Robert Downey Jr." }, actorB: { id: 2524,  name: "Al Pacino"         }, sharedFilm: "Two for the Money" },
  { date: "2025-01-24", actorA: { id: 31,    name: "Tom Hanks"         }, actorB: { id: 7167,  name: "Meg Ryan"          }, sharedFilm: "You've Got Mail" },
  { date: "2025-01-25", actorA: { id: 2888,  name: "Hugh Jackman"      }, actorB: { id: 1245,  name: "Scarlett Johansson"}, sharedFilm: "The Prestige" },
  { date: "2025-01-26", actorA: { id: 1892,  name: "Nicole Kidman"     }, actorB: { id: 500,   name: "Tom Cruise"        }, sharedFilm: "Far and Away" },
  { date: "2025-01-27", actorA: { id: 8784,  name: "Daniel Day-Lewis"  }, actorB: { id: 4724,  name: "Heath Ledger"      }, sharedFilm: "Gangs of New York" },
  { date: "2025-01-28", actorA: { id: 2524,  name: "Al Pacino"         }, actorB: { id: 2231,  name: "Edward Norton"     }, sharedFilm: "The Italian Job" },
  { date: "2025-01-29", actorA: { id: 192,   name: "Morgan Freeman"    }, actorB: { id: 31,    name: "Tom Hanks"         }, sharedFilm: "Cast Away" },
  { date: "2025-01-30", actorA: { id: 500,   name: "Tom Cruise"        }, actorB: { id: 192,   name: "Morgan Freeman"    }, sharedFilm: "Born on the Fourth of July" },
  { date: "2025-01-31", actorA: { id: 73457, name: "Chris Evans"       }, actorB: { id: 1245,  name: "Scarlett Johansson"}, sharedFilm: "Captain America: The Winter Soldier" },
  { date: "2025-02-01", actorA: { id: 1158,  name: "Robert De Niro"    }, actorB: { id: 31,    name: "Tom Hanks"         }, sharedFilm: "Road to Perdition" },
  { date: "2025-02-02", actorA: { id: 2037,  name: "Meryl Streep"      }, actorB: { id: 5064,  name: "Cate Blanchett"    }, sharedFilm: "The Aviator" },
  { date: "2025-02-03", actorA: { id: 6384,  name: "Keanu Reeves"      }, actorB: { id: 2231,  name: "Edward Norton"     }, sharedFilm: "The Italian Job" },
  { date: "2025-02-04", actorA: { id: 3084,  name: "Jack Nicholson"    }, actorB: { id: 2524,  name: "Al Pacino"         }, sharedFilm: "Hoffa" },
  { date: "2025-02-05", actorA: { id: 287,   name: "Brad Pitt"         }, actorB: { id: 1158,  name: "Robert De Niro"    }, sharedFilm: "Meet Joe Black" },
  { date: "2025-02-06", actorA: { id: 1245,  name: "Scarlett Johansson"}, actorB: { id: 3223,  name: "Robert Downey Jr." }, sharedFilm: "Iron Man 2" },
  { date: "2025-02-07", actorA: { id: 4724,  name: "Heath Ledger"      }, actorB: { id: 5064,  name: "Cate Blanchett"    }, sharedFilm: "I'm Not There" },
  { date: "2025-02-08", actorA: { id: 7167,  name: "Meg Ryan"          }, actorB: { id: 31,    name: "Tom Hanks"         }, sharedFilm: "Sleepless in Seattle" },
  { date: "2025-02-09", actorA: { id: 2975,  name: "Laurence Fishburne"}, actorB: { id: 6384,  name: "Keanu Reeves"      }, sharedFilm: "The Matrix Reloaded" },
  { date: "2025-02-10", actorA: { id: 16828, name: "Bill Murray"       }, actorB: { id: 1245,  name: "Scarlett Johansson"}, sharedFilm: "Lost in Translation" },

  // 2026-06 playtest entries — all IDs verified against TMDB API
  { date: "2026-06-09", actorA: { id: 1158,  name: "Al Pacino"         }, actorB: { id: 819,   name: "Edward Norton"     }, sharedFilm: "The Italian Job" },
  { date: "2026-06-10", actorA: { id: 3894,  name: "Christian Bale"    }, actorB: { id: 6968,  name: "Hugh Jackman"      }, sharedFilm: "The Prestige" },
  { date: "2026-06-23", actorA: { id: 1158,  name: "Al Pacino"         }, actorB: { id: 380,   name: "Robert De Niro"    }, sharedFilm: "Heat" },
  { date: "2026-06-24", actorA: { id: 500,   name: "Tom Cruise"        }, actorB: { id: 4483,  name: "Dustin Hoffman"    }, sharedFilm: "Rain Man" },
  { date: "2026-06-25", actorA: { id: 6968,  name: "Hugh Jackman"      }, actorB: { id: 1245,  name: "Scarlett Johansson"}, sharedFilm: "The Prestige" },
  { date: "2026-06-26", actorA: { id: 3894,  name: "Christian Bale"    }, actorB: { id: 192,   name: "Morgan Freeman"    }, sharedFilm: "The Dark Knight" },
  { date: "2026-06-27", actorA: { id: 112,   name: "Cate Blanchett"    }, actorB: { id: 287,   name: "Brad Pitt"         }, sharedFilm: "Babel" },
  { date: "2026-06-28", actorA: { id: 5064,  name: "Meryl Streep"      }, actorB: { id: 380,   name: "Robert De Niro"    }, sharedFilm: "The Deer Hunter" },
  { date: "2026-06-29", actorA: { id: 6384,  name: "Keanu Reeves"      }, actorB: { id: 1158,  name: "Al Pacino"         }, sharedFilm: "The Devil's Advocate" },
];
